version: "2.1"

services:
  compile:
    build: .
    command: dpkg-buildpackage -us -uc
    environment:
      LANG: en_US.UTF-8
    volumes:
      - ../:/apps/cassandra-sstable-tools
      - ../dest:/apps
    working_dir: /apps/cassandra-sstable-tools
